- .github/PULL_REQUEST_TEMPLATE.md
Please review Pull Request Template
> Initial Pull request template create

- src/api/.gitignore
- src/api/express.ts
- src/api/package-lock.json
- src/api/package.json
- src/api/routes/health-routes.ts
- src/api/server.ts
- src/api/tsconfig.json
- Initial folder hierarchy setup for API
- Initial API configuration
- Initial setup of TypeScript
- Health end point added to API
- setup of .env usage
- adding initial packages for development: Express, Nodemon, Concurrently, typescript, dotenv 
- setup of .gitignore 
- Manual testing of end point using ThunderClient and browser
- Visually checked the correct port loaded from .env and not the backup
> Way finder init setup initial api

- README.md
- package-lock.json
- package.json
- src/api/package-lock.json
- [X ] Refactoring / Documentation
- [ X] N/A
> Wayfinder init add readme

- src/api/.env.template
- src/api/README.md
-Added README to API section of repo
-Added .env.template to help facilitate adoption of repo
> Created init readme for API

- docker-compose.yaml
> docker-compose updated to include frontend image

- docker-compose.yaml
- src/api/Dockerfile
- src/frontend-pwa/Dockerfile
I added healthchecks to both the api and app portion of the docker-compose.yaml.
I also had to add curl to both api and frontend dockerfiles to do said healthchecks.
> Wayfinder init docker compose healthcheck

- README.md
> Changing Title of Readme

- .github/workflows/api-build-deploy.yaml
Added api-build-deploy.yaml to .github/workflows
> [WAYF-45] - openshift setup

- src/api/Dockerfile
Using staff purchaing dockerfile example to build and deploy api image
> [WAYF-45] - Update API dockerfile

- OpenShift/templates/wf-api-dc-template.yaml
Updated values fix template auth
> Fixed template issue

- src/frontend-pwa/Dockerfile
Updated frontend dockerfile to fix root issue
> Frontend dockerfile updated to fix root issue

- .github/workflows/api-build-deploy.yaml
- .github/workflows/frontend-PWA-build-deploy.yaml
added "healthcheck" and "cleanup" jobs to the frontend yaml file
> Wayf 45 openshift frontend workflow yaml

- src/frontend-pwa/Dockerfile
> Updated frontend dockerfile

- OpenShift/templates/wf-api-dc-template.yaml
- Updated the API Template for openshift to reduce our resource footprint
> [WAYF-47] Added resource limits to api template

- OpenShift/templates/wf-api-dc-template.yaml
> [WAYF-47]Update api template to always deploy

- OpenShift/templates/wf-app-dc-template.yaml
Added OpenShift template for the frontend
> Wayf 45 app dc template

- .github/workflows/frontend-PWA-build-deploy.yaml
added deploy, healtcheck, and cleanup jobs to frontend-pwa workflow
> added deploy,healthcheck,cleanup jobs to workflow

- OpenShift/templates/wf-app-dc-template.yaml
Updated the OpenShift/templates/wf-app-dc-template.yaml
> Updated OpenShift/template/wf-app-dc-template.yaml

- OpenShift/templates/wf-api-dc-template.yaml
Fixed indentation that is likely causing issues
> [WAYF-47] Fixed overlooked indention issue

- OpenShift/templates/wf-app-dc-template.yaml
Fixed an issue in wf-app-dc-template.yaml
> Fixed issue in wf-app-dc-template.yaml

- .github/workflows/api-build-deploy.yaml
Added the ability to send Success and Failure messages to Teams when deploying the API.
> Wayf 46 teams deploy message

- .github/workflows/api-build-deploy.yaml
- .github/workflows/frontend-PWA-build-deploy.yaml
Added the ability to send success and failure messages to a Teams channel for the frontend app
> Added Success and Failure messages to frontend-pwa-build-deploy.yaml

- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/components/Header/Header.tsx
- src/frontend-pwa/src/main.tsx
Frontend files: App.tsx, main.tsx and Header.tsx were updated to follow AirBNB Style guidelines.
> Wayf 90 frontend air bnb

- docker-compose.yaml
- src/mongoSeed/init/create-db.js
- Updated the Seed data for MongoDB to give a list of 5 generic locations for local development
- Updated the Docker-compose for DB since it was overwriting existing data
- Manually inspected in the Mongo container CLI
> Updated Docker-compose for Mongo, added seed data

- src/mongoSeed/init/create-db.js
- Branch was merged before feedback had been addressed
> [WAYF-74] Added newline

- src/frontend-pwa/package.json
- src/frontend-pwa/src/components/Header/header.styles.ts
- src/frontend-pwa/src/typography.tsx
Added necessary file typography.tsx to import and use BCSans
> Wayf 50 header update

- src/api/controllers/location-controller.ts
- src/api/db.ts
- src/api/models/index.ts
- src/api/models/singleLocation-model.ts
- src/api/types/SingleLocation.ts
- src/api/types/index.ts
- modified Mongoose connection string to specify db to use
- /locations endpoint sends data from MongoDB instead of locally
- Created SingleLocation mongoose schema from previous type (Subject to future changes)
> [WAYF-75] Integrated locations endpoint with Mongoose

- src/frontend-pwa/index.html
- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/components/Button/Button.tsx
- src/frontend-pwa/src/components/Button/button.styles.ts
WAYF-52-add-button-component
--note: "no nested ternary operators" eslint rule bypassed, refactor later
> Wayf 52 add button component

- src/frontend-pwa/src/components/Footer/Footer.tsx
- src/frontend-pwa/src/components/Footer/footer.styles.ts
> Footer.tsx and footer.styles.ts updated to remove links

- src/api/models/singleLocation-model.ts
- src/api/types/SingleLocation.ts
- src/mongoSeed/init/create-db.js
- Updating location data models used by the API to reflect those being created by the Web Scraping tool in development to further facilitate creation of the frontend
> [WAYF-93] update api models + mongo seed

- src/frontend-pwa/package.json
- src/frontend-pwa/src/views/Report/Report.tsx
MUI (Material UI) has been added to the project dependencies. An Example import for a text field has been added to the Report View for Tylers form. 
> Wayf 71 m UI install

- src/frontend-pwa/src/views/Report/Report.tsx
Fix for eslint issue of importing textfield without using it.
> Fixed unused Textfield import in Report View

- src/api/controllers/report-controller.ts
- src/api/express.ts
- src/api/routes/index.ts
- src/api/routes/report-router.ts
This is only some stub functionality for a later feature. The purpose of the stub function is to help the frontend with creating their report component by giving them the endpoint they'll be developing towards, and having it echo back to make sure what is being sent is intended and formatted correctly.
Swagger documentation is not included at this time, as another (My next) ticket has updating all Swagger Documentation for new models and things.
> Added /report stub endpoint for development

- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/components/Spinner/Spinner.tsx
- src/frontend-pwa/src/components/Spinner/spinner.styles.ts
- src/frontend-pwa/src/components/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/components/SplashScreen/splashscreen.styles.ts
- Created Basic Spinner component for displaying loading (Can be built up later to have variants if needed)
- Added SplashScreen which will conditionally render is isLoading is set to true. 
> [Wayf 53] splashscreen

- src/api/config/corsConfig.ts
- src/api/config/index.ts
- src/api/express.ts
- src/api/package.json
- Added CORS to API
- compartmentalized the import into config file and express
> [WAYF-96] added cors to api

- docker-compose.yaml
- src/frontend-pwa/nginx.conf
- src/frontend-pwa/src/App.tsx
- Updated environment variables for Docker
- Added ESLInt ignore rule temporarily during dev in App
> [WAYF-64] update nginx so fetch works in docker

- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/Type/CurrentLocation.ts
- src/frontend-pwa/src/Type/LocationsArray.ts
- src/frontend-pwa/src/Type/MultipleLocations.ts
- src/frontend-pwa/src/Type/SingleLocation.ts
- src/frontend-pwa/src/Type/index.ts
- src/frontend-pwa/src/components/ListItem/ListItem.tsx
- src/frontend-pwa/src/components/ListItem/listitem.styles.ts
- src/frontend-pwa/src/components/ListItems/ListItems.tsx
- src/frontend-pwa/src/components/ListItems/listitems.style.ts
- src/frontend-pwa/src/routes/ViewRouter.tsx
- src/frontend-pwa/src/utils/CalcDistance.ts
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/Location/location.styles.ts
- Created ListItem component to display location data
- Created ListItems component to display a list of the ListItem component
- Styled both components
- Created a function in the utils folder to get the distance between the users current location and the listItem location
- Increased the Splashcreen timer as per Roberts request for the sprint review to better see the splashScreen
- Updated the ViewRouter to be able to pass props to different views
- Updated the Location view to display the List of locations
> [Wayf 65] FEATURE list item

- src/frontend-pwa/Dockerfile
- Delete unused comment in frontend dockerfile
> [Wayf 68] HOTFIX dockerfile cleanup

- .github/PULL_REQUEST_TEMPLATE.md
- Changing the PR Template to one that is more digestable, and better communicates across the extended Wayfinder team
> [WAYF-46] FEATURE** Updated Pull Request Template

- src/api/config/index.ts
- src/api/config/rateLimitConfig.ts
- src/api/express.ts
- src/api/middleware/globalErrorHandler.ts
- src/api/middleware/index.ts
- src/api/package.json
- Added a basic Global Error Handler to Express API to override the default response
- Added basic (overdue) rate limiting to Express API.
> [WAYF-134] FEATURE** Rate Limiting + Basic Error handler added

- src/api/config/corsConfig.ts
- src/api/controllers/analytic-controller.ts
- src/api/db.ts
- src/api/express.ts
- src/api/public/routeDocs/analytic.yaml
- src/api/public/routeDocs/responses/responses.yaml
- src/api/routes/analytic-router.ts
- src/api/routes/index.ts
- src/api/utils/validationErrorHandler.ts
- Updated Swagger Documentation for analytics endpoint
- Generic Responses file created for Swagger
- Analytic endpoint writes to database using Mongoose Schema for validation/cleansing
- CORS modified to disallow non-application use
- Creation of a ValidationError handler to prevent future redundancy in development
> [WAYF-126] FEATURE** Create analytic endpoint

- src/frontend-pwa/public/robots.txt
- src/frontend-pwa/src/main.tsx
- src/frontend-pwa/tsconfig.json
- src/frontend-pwa/vite.config.js
- Did some research into the service workers and added some slight configuration changes in hopes of improving the caching functionality. 
- Service worker running on actual script instead of random html headers (found through Application page)
- Increased App size from **select** files to **all** files 500kb -> 2.1mb. 
- App appears to function/cache better across both my devices with the changes
> [WAYF-139] FEATURE** Improve Service Worker Caching

- src/api/config/corsConfig.ts
- src/frontend-pwa/index.html
- src/frontend-pwa/src/main.tsx
- src/frontend-pwa/vite.config.js
- Fixed CORS rules regarding localhost development
- fixed a rule in service worker that was overriding an 'auto' setting causing undefined behaviour
- removed an import in index.html that didnt need to exist since the service worker now injects that line when building prod (causing 404 errors)
> [WAYF-139] HOTFIX** fix Service Worker + CORS

- src/frontend-pwa/src/components/Button/Button.tsx
- src/frontend-pwa/src/components/Button/button.styles.ts
- src/frontend-pwa/src/components/SearchBar/SearchBar.tsx
- src/frontend-pwa/src/components/SearchBar/searchbar.styles.ts
- src/frontend-pwa/src/views/Eula/eula.styles.tsx
- added a "@summary" to files i have worked on, per robert's request.
-
> [WAYF-104] DOCS** Update Code Documentation

- src/frontend-pwa/src/views/Home/Home.tsx
- Changed text in a button per PO request. 
New
Old
> [WAYF-155] HOTFIX** Change text in a button

- src/frontend-pwa/src/components/ListItems/ListItems.tsx
- src/frontend-pwa/src/components/LocationListItem/LocationListItem.tsx
- src/frontend-pwa/src/components/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/constants/Constants.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/utils/AppLocalStorage.ts
- src/frontend-pwa/src/utils/CalcDistance.ts
- src/frontend-pwa/src/utils/OnlineCheck.ts
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
-Added a server side check using the API Health endpoint to determine if the device is online or not
-If App is online, new data is pulled from the API and saving it to local storage as well as saving the current location
-If App in offline the data and current location is set from local storage
-Refactored setAppData to take a boolean as a prop that determines is the app is online or not and proceeds accordingly
-Updated the CalcDistance function to implement new currentLocation and added some error handling
-Updated comments
-Added some error handling to BCServies and locations views in case appData in localStorage gets deleted
> [WAYF-114] FEATURE** Initial Offline Functionality

- src/frontend-pwa/src/views/AboutContact/AboutContact.tsx
- src/frontend-pwa/src/views/AboutContact/aboutcontact.styles.ts
- No functionality changes
- Added Bio for Jesse to the about/contact page
- Updated content of about/contact per Jesse's revisions
> [WAYF-132] FEATURE** Revise About Section Content

- src/frontend-pwa/src/constants/Constants.ts
- removed a single exclamation mark
> [WAYF-105] HOTFIX** fixed constants

- src/frontend-pwa/src/components/LocationListItem/LocationListItem.tsx
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/utils/CalcDistance.ts
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/Location/location.styles.ts
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Added mapping component to Location View
- Added  searchbar and filtering to location View
- Implemented Location Range from settings to filter out locations that are further away then the location range
- Updated LocationListItems component accordingly
- Added styling from BCServices view to have a consistent feel
> [WAYF-102] FEATURE** Location Service Refine

- src/frontend-pwa/src/utils/CalcDistance.ts
- src/frontend-pwa/src/views/Location/Location.tsx
- CalcDistance function no longer calls custom useAppSevice hook directly 
- currentLocation is now passed to CalcDistance as a prop
> [WAYF-102] HOTFIX** Location View Refinement 

- src/frontend-pwa/src/components/Header/header.styles.ts
- src/frontend-pwa/src/components/ListItems/listitems.style.ts
- src/frontend-pwa/src/components/Mapping/mapping.styles.ts
- src/frontend-pwa/src/components/Slider/slider.styles.ts
- src/frontend-pwa/src/constants/mq.tsx
- src/frontend-pwa/src/views/AboutContact/aboutcontact.styles.ts
- src/frontend-pwa/src/views/BCServices/bcservices.styles.ts
- src/frontend-pwa/src/views/Eula/eula.styles.tsx
- src/frontend-pwa/src/views/Location/location.styles.ts
- src/frontend-pwa/src/views/Settings/settings.styles.ts
- Added a mq object to the constants folder that contains media query breakpoints for mobile, tablet and desktop screen sizes
- Replaced hardcoded max and min width values where necessary
- Some values still remain hardcoded as they are unique stylings for specific components
> [WAYF-148] FEATURE** Media Query Breakpoints

- src/frontend-pwa/src/Type/SingleLocation.ts
- src/frontend-pwa/src/views/Location/Location.tsx
- Taking suggestions from Jesse, refactor the Location view
- Refactored Locations view to show locations based on distance instead of alphabetically
- corrected SingleLocation file to use `string` and not `String` in its definitions.
> [WAYF-172] FEATURE** sort 'Locations' view by shortest distance

- src/frontend-pwa/src/views/Report/Report.tsx
- src/frontend-pwa/src/views/Report/report.styles.ts
- Updated the event reporting form to provide a base level of information, and to submit that information to an endpoint.
- ![cap1](https://github.com/bcgov/citz-imb-wayfinder/assets/123214152/0bb8a145-a82a-4267-a0fd-30ee9181b604)
> [WAYF-108] FEATURE** Enhance Report View

- src/frontend-pwa/src/components/Button/button.styles.ts
- src/frontend-pwa/src/views/Report/Report.tsx
- src/frontend-pwa/src/views/Report/report.styles.ts
- added `not-allowed` pointer to Button on disabled
- set select menu to inherit background color to remove odd gray colour
- added one constant for minCharLimit instead of hardcoding
- Added `mq` object for to replace standard media queries
> [WAYF-108] HOTFIX** Light CSS tweaks to report

- src/api/types/Analytic.ts
- src/frontend-pwa/src/Type/Analytic.ts
- src/frontend-pwa/src/components/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/services/app/AppReducer.ts
- src/frontend-pwa/src/utils/Analytics.ts
- src/frontend-pwa/src/views/Report/Report.tsx
- Analytics function created in utils that posts data to the analytic endpoint
- Analytics object created and passed to Analytic function in Report view
- Minor comment changes to unrelated files
> [WAYF-113] FEATURE** Analytics Stub

- src/frontend-pwa/src/components/Mapping/Mapping.tsx
- display lat and long on user marker
> [WAYF-XXX] HOTFIX** adding lat/long to user marker

- src/api/controllers/location-controller.ts
- src/api/public/routeDocs/locations.yaml
- src/api/tests/locations.test.js
- API returns a consolidated list of services to assist in the future refactoring of the 'Find BC Service' option in app
- Swagger Documentation includes new update
- Jest test verifies that 'allServices' part of the response
> [WAYF-177] FEATURE** add 'allServices' to API seed return

- src/api/controllers/report-controller.ts
- src/api/models/report-model.ts
- src/api/public/routeDocs/report.yaml
- src/api/public/schemaDocs/Report-Schema.yaml
- src/api/tests/analytic.test.js
- src/api/tests/report.test.js
- Switched /report endpoint from echoing data to actually storing it
- added tests for different levels of (in)valid data being sent to report endpoint
- updated swagger docs
- added cleanup to endpoint for all `APITests` to be deleted
> [WAYF-163] FEATURE** Add API 'Report' Functionality

- src/frontend-pwa/src/components/common/Header/Header.tsx
- src/frontend-pwa/src/components/common/Header/header.styles.ts
- Wayfinder Header now links to homepage
- Logo and settings/back button positions swapped
> [WAYF-170] FEATURE** Header Nav Link

- src/frontend-pwa/src/components/utility/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- Implemented Offline mode from settings
- Reworked splashscreen to check if offline mode is enabled and proceed accordingly
- Removed console.log from useAppService from last PR
- Added the offline mode state check to the conditional rendering in the Office and BCServices views
> [WAYF-169] FEATURE** Offline Setting

- src/frontend-pwa/src/components/utility/SplashScreen/SplashScreen.tsx
- There was some re-rendering that was happening which was not picked up in dev.
- The issue seemed to be where the isLoading state was being set
> [WAYF-169] HOTFIX** For re-renders

- src/frontend-pwa/src/Type/SingleLocation.ts
- src/frontend-pwa/src/Type/index.ts
- src/frontend-pwa/src/components/common/Button/button.styles.ts
- src/frontend-pwa/src/components/lists/LocationListItem/LocationListItem.tsx
- src/frontend-pwa/src/components/utility/Mapping/Mapping.tsx
- src/frontend-pwa/src/components/utility/Mapping/mapping.styles.ts
- src/frontend-pwa/src/routes/ViewRouter.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/LocationInformation/LocationInformation.tsx
- src/frontend-pwa/src/views/LocationInformation/locationInformation.style.ts
- Added Additional View to display the information about a location
- Modified Mapping component to link to LocationInformation View
- Modified Location list items to link to LocationInformation View
- LocationInformation View uses URL Params
- LocationInformation View displays Stub 404 if invalid params entered (Future ticket to make a View for that)
Screenshots:
Modified Map
Desktop View of LocationInformation
Mobile view of LocationInformation
> [ WAYF-185 ] FEATURE** LocationInformation View

- src/frontend-pwa/src/components/utility/Greeting/Greeting.tsx
- src/frontend-pwa/src/components/utility/Greeting/greeting.style.ts
- src/frontend-pwa/src/views/Home/Home.tsx
- src/frontend-pwa/src/views/Home/home.styles.ts
- Moved Greeting into its own Component
- Swapped `Math.Random()` to `Date.now()` due to SSR conflicts
- Adjusted CSS to Greeting component
> [WAYF-189] FEATURE-FIX** Adjust Greetings text in Main View

- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- Implemented location range filter in BCServices view
> [WAYF-162] FEATURE** Implemented location range

- src/api/controllers/report-controller.ts
- src/api/models/report-model.ts
- src/api/public/routeDocs/report.yaml
- src/api/types/Report.ts
- Report now returns the Report with the ID listed as ticketNum for reference + readability. Future implementations will let it be stored and viewed on the user's device.
- Update Swagger docs 
- tidied up + corrected the self-cleaning from running tests
> [WAYF-193]FEATURE**  Add Ticket numbers + return reports to user

- docker-compose.yaml
- src/api/controllers/analytic-controller.ts
- src/api/controllers/report-controller.ts
- src/api/routes/analytic-router.ts
- src/api/routes/report-router.ts
- Added get methods to pull the data from analytics / Report endpoints
- uses a 32-byte password to protect endpoints (will likely strengthen later, but something for meantime)
> [WAYF-192] Add get methods to Report/Analytic Endpoints

- src/api/controllers/location-controller.ts
- src/api/public/routeDocs/locations.yaml
- src/frontend-pwa/src/components/utility/Mapping/Mapping.tsx
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- Edited 'Key' for locations since ICBC information does not contain unique web addresses compared to when using serviceBC as the model
- Edited API Location returns to include ICBC data
- Edited Frontend since 'Services' view wasn't using the newer scalable data sets
- Updated Swagger docs for the /locations end
> [WAYF-166] FEATURE+FIX** Make ICBC Data accessible (Minor Tweaks)

- src/scraper/servicebc_scraper.py
- ServiceBC Changed their website slightly for when limited services are offered. I have made the adjustments
> [N/A] HOTFIX** Scraper adjustment

- src/frontend-pwa/src/components/appNav/NavButton/navButton.styles.ts
- src/frontend-pwa/src/components/common/Footer/Footer.tsx
- src/frontend-pwa/src/components/common/SearchBar/SearchBar.tsx
- src/frontend-pwa/src/components/utility/Greeting/Greeting.tsx
- src/frontend-pwa/src/components/utility/Mapping/Mapping.tsx
- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/views/AboutContact/AboutContact.tsx
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Eula/Eula.tsx
- src/frontend-pwa/src/views/Home/Home.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/LocationInformation/LocationInformation.tsx
- src/frontend-pwa/src/views/NotFound/NotFound.tsx
- src/frontend-pwa/src/views/OfficeOptionsView/OfficeOptionsView.tsx
- src/frontend-pwa/src/views/Report/Report.tsx
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Updated all components in application to use the `content.ts` file
- Added a temporary useState in all components defaulted to English to help with the transition to Multi-language (replace later with actually user settings)
- Translated all the content in the app to french
- Fully Scalable to add more languages, only modifying the `content.ts` file
- Fixed the mapping icons so they arent stretched out
If you want to test it, open any file and switch the `lang` useState from `eng` to `fr`
> [WAYF-201] FEATURE** Language Support

- src/frontend-pwa/src/Type/SettingsObject.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Added language to settings
- Updated the select to display the correct language option
- Next ticket will use the settings throughout the app
> [WAYF-203] FEATURE** Language Select in settings

- src/frontend-pwa/src/components/common/Footer/Footer.tsx
- src/frontend-pwa/src/components/common/SearchBar/SearchBar.tsx
- src/frontend-pwa/src/components/utility/Greeting/Greeting.tsx
- src/frontend-pwa/src/components/utility/Mapping/Mapping.tsx
- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/views/AboutContact/AboutContact.tsx
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Eula/Eula.tsx
- src/frontend-pwa/src/views/Home/Home.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/LocationInformation/LocationInformation.tsx
- src/frontend-pwa/src/views/NotFound/NotFound.tsx
- src/frontend-pwa/src/views/OfficeOptionsView/OfficeOptionsView.tsx
- src/frontend-pwa/src/views/Report/Report.tsx
- Replaced all temporary test useStates with proper language settings state
> [WAYF-204] FEATURE** App uses language settings

- src/frontend-pwa/src/components/utility/Mapping/Mapping.tsx
- src/frontend-pwa/src/views/LocationInformation/LocationInformation.tsx
- Edited URL Param so serviceTypes are compared in all Lowercase format.
> [N/A] HOTFIX** Changed URL filtering in LocationInformation

- src/frontend-pwa/src/content/content.ts
- fix variable mismatch in report.tsx
> [WAYF-201] HOTFIX** variable mismatch

- src/frontend-pwa/src/Type/Report.ts
- src/frontend-pwa/src/Type/SettingsLocalStorage.ts
- src/frontend-pwa/src/constants/Constants.ts
- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/services/app/AppActions.ts
- src/frontend-pwa/src/services/app/AppReducer.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/utils/LocalStorageSettingsCheck.ts
- src/frontend-pwa/src/views/Report/Report.tsx
- Successful reports are saved to local storage and are added to state to be used by report history later
- Successful reports display their ticket numbers
- Updated comments
> [WAYF-194] FEATURE** Reports Saved to Device

- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/components/common/MoreInfoButton/MoreInfoButton.tsx
- src/frontend-pwa/src/components/utility/BannerTip/BannerTip.tsx
- src/frontend-pwa/src/components/utility/BannerTip/bannerTip.style.ts
- src/frontend-pwa/src/services/app/AppActions.ts
- src/frontend-pwa/src/services/app/AppReducer.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Made necessary changes to add toolTipText/setToolTipText to state
- Moved BannerTip to root so it's available everywhere
> [WAYF-226] FEATURE** Global BannerTip

- OpenShift/templates/wf-api-dc-template.yaml
- src/api/db.ts
- slight bump to API resources (25Mi) to handle multi-queries (we are living on scraps)
- added more connection handlers for reconnections / closing
> [N/A] HOTFIX** Mongoose connection fixes + (slight) resource bump

- src/frontend-pwa/index.html
- src/frontend-pwa/vite.config.js
- Changed name of Application from `Wayfinder` to `BC Wayfinder`
> [N/A] Application name change

- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/views/AboutContact/AboutContact.tsx
- Slight refactoring to About section
- only text content changed
> [N/A] TEXT CONTENT** Add Special thanks in About section

- src/api/controllers/location-controller.ts
- src/api/db.ts
- src/api/models/index.ts
- src/api/models/update-model.ts
- src/api/public/routeDocs/account.yaml
- src/api/public/routeDocs/locations.yaml
- src/api/routes/location-router.ts
- src/api/types/UpdateDate.ts
- src/api/types/index.ts
- src/api/utils/extractServiceList.ts
- src/api/utils/servicesOffered.ts
- Updated the /locations POST method to take in an `updateArr` containing `UpdateDate` type objects. 
- Endpoint returns a list of location data where the the UpdateDate objects don't match
The result of this PR is that the API can send curated sets of data when and only if a dataset is updated, this helps reduce overall data consumption for the mobile device.
> [WAYF-232] FEATURE** new POST method on /locations to reduce data load

- src/api/models/analytic-model.ts
- src/api/public/schemaDocs/Analytic-Schema.yaml
- src/api/types/Analytic.ts
- Updated the model for gathering analytics to have a wider net to cast in what we capture, and display.
- no breaking changes made to the frontend caused by the expanded model.
- Swagger docs updated to show the changed values
> [WAYF-239] UPDATE** Update the Analytics Model

- src/mongoSeed/init/create-db.js
- Updated the seed data for the database to populate data for the 5 current values we're displaying.
- Added two stub reports to seed
- Added the updateDates data to the database seed
> [WAYF-237] UPDATE** Update seed data

- src/frontend-pwa/package.json
- src/frontend-pwa/src/content/changelogContent.ts
- src/frontend-pwa/src/routes/ViewRouter.tsx
- src/frontend-pwa/src/views/WhatsNew/WhatsNew.tsx
- src/frontend-pwa/src/views/WhatsNew/whatsNew.styles.ts
- Added a What's new section to showcase what has changed between previous versions
- Accessible from the Settings menu
It is minimalist, simple, and a changelog
> [WAYF-231] FEATURE** "What's New"

- src/frontend-pwa/src/components/common/Button/button.styles.ts
- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/views/NotFound/NotFound.tsx
- Changed the text content of 404 button from "Go Home" to "Main Page", also added French (oops)
- increased width of small button from 100 -> 125
> [WAYF-244-] MINOR** Change the text in 404 page button

- src/frontend-pwa/index.html
- src/frontend-pwa/src/index.css
- src/frontend-pwa/vite.config.js
- Added keywords and updated descriptions
- Can't really improve SEO beyond that since you're locked into a Terms and Conditions page for a first time load. Robots don't like to sign T&C.
- Added one CSS rule to body to get rid of a lingering scrollbar
> [WAYF-178] CONTENT** Updated SEO

- src/api/models/analytic-model.ts
- src/api/public/schemaDocs/Analytic-Schema.yaml
- src/api/types/Analytic.ts
- src/frontend-pwa/src/App.tsx
- src/frontend-pwa/src/Type/Analytic.ts
- src/frontend-pwa/src/Type/StateObject.ts
- src/frontend-pwa/src/components/utility/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/utils/AppAnalytics.ts
- src/frontend-pwa/src/utils/UpdateOnLoad.tsx
- src/frontend-pwa/src/views/Eula/Eula.tsx
- src/frontend-pwa/src/views/Location/Location.tsx
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Analytic model Updated slightly to capture app launches
- Refactored Splash Screen to capture app launch analytics and loading data/state
- New UpdateOnLoad util created to update app data/state
- Eula Updated to capture new user analytics 
- Location updated to capture distance to analytics
- Updated Settings view to capture individual setting analytics
> [WAYF-224] FEATURE** Add Analytic Stubs

- src/api/models/analytic-model.ts
- src/frontend-pwa/src/components/common/Accordion/Accordion.tsx
- src/frontend-pwa/src/views/AboutContact/AboutContact.tsx
- src/frontend-pwa/src/views/BCServices/BCServices.tsx
- src/frontend-pwa/src/views/Eula/Eula.tsx
- src/frontend-pwa/src/views/LocationInformation/LocationInformation.tsx
- src/frontend-pwa/src/views/ReportHistory/ReportHistory.tsx
- src/frontend-pwa/src/views/Settings/Settings.tsx
- src/frontend-pwa/src/views/WhatsNew/WhatsNew.tsx
- Added Settings analytics
- Added report history analytics
- Added About analytics
- Added what's new analytics
- Added Find service analytics
- updated accordion to take an optional function
- updated analytic model accordingly
> [WAYF-224] FEATURE** More Analytics

- src/frontend-pwa/src/components/utility/SplashScreen/SplashScreen.tsx
- src/frontend-pwa/src/constants/Constants.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- src/frontend-pwa/src/utils/UpdateOnLoad.tsx
- Added an event listener to check for when the app gets installed. An app installed is than added to local storage
- Added a check to see if the install prompt is still there. if so, check to see if the app installed key is in the local storage. and delete local storage accordingly
> [WAYF-186] FEATURE** Local storage clear on delete

- src/frontend-pwa/src/content/content.ts
- src/frontend-pwa/src/views/Settings/Settings.tsx
- Added missing tooltip to the refresh setting
> [WAYF-245] HOTFIX** Added tool tip

- src/api/controllers/location-controller.ts
- src/frontend-pwa/src/constants/Constants.ts
- src/frontend-pwa/src/services/app/useAppService.ts
- Refactored logic in setAppData to reduce load on api
> [WAYF-223] FEATURE** reduce load

- src/frontend-pwa/src/content/changelogContent.ts
- edited the "What's New" page to be less verbose, fixed a typo.
- { Include any screenshots necessary }
> [WAYF-218] HOTFIX** Code Cleanup
